### ISSUE TITLE
tsp-web does not find any local tasks

### ISSUE THREAD

**Issue by ryusko2** [BrunnerLivio/tsp-web#9]
Okay not sure what I'm doing wrong here ... cloned this repository (because `sudo npm install -g tsp-web` gave a _not found in repository_ error) and `npm install`ed from the local directory.

`tsp-web start --startup` does indeed start a local web server that I can see on `localhost:3000`, but no tasks I run in a _local_ instance of `tsp` show up on the list (actually I can't get any to show up no matter how I run `tsp`).  I had originally tried starting `tsp-web` from an SSH session, but now I've tried both, and neither one seems to populate at all.

My `tsp` is installed from Arch's AUR, and running tasks as specified in help (i.e. `tsp -L OK ls && tsp -L WAIT sleep 30`) show up in the `tsp` list correctly (from CLI), with incremented IDs ... they just never make it to `tsp-web`.  

System details:
- npm 8.19.1
- Arch Linux 5.15.65-lts x86_64

Not sure what else you need to troubleshoot, but let me know and I will provide what information I can :)

**Comment by berezovskyi** [comment]
I was just able to get it running from the first try (no code changes, running from source) using Node 14 (`fnm install lts/fermium`) on an RPi 4 (`Linux 6.1.21-v8+ aarch64`). Both job listing and log output work fine (though large logs have trouble to render well, though I see it as a perf issue, not a bug; Chrome is a bit better than Firefox).

More info:

```
$ npm -v
6.14.18
$ node -v
v14.21.3
$ tsp -V
Task Spooler v1.0.1 - a task queue system for the unix user.
Copyright (C) 2007-2020  Lluis Batlle i Rossell
```

**Comment by BrunnerLivio** [comment]
I just published the library on NPM:
https://www.npmjs.com/package/tsp-web

Seems like it was never published. Though I can't get it running via NPM at the moment myself (it's a 7 year old project) :) 
Locally it still works perfectly fine using Node v16/v18

**Comment by BrunnerLivio** [comment]
Okay now everything should work as expected! You can run it via:

```bash
npm i -g tsp-web
tsp-web start
# or run it on startup:
tsp-web start --startup
```

I also added a changelog that also has the Debian package attached.
